name: menu_mind
description: "Smart Menu Translator with Cultural Insight, Ingredient Prediction, and Allergy Detection"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  cupertino_icons: ^1.0.8

  # AI Inference
  flutter_gemma: ^0.10.1

  # State Management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.3

  # Camera & Image
  camera: ^0.10.5+9
  image_picker: ^1.0.7
  image: ^4.1.7

  # Text-to-Speech
  flutter_tts: ^3.8.5

  # UI & Fonts
  google_fonts: ^6.1.0
  flutter_hooks: ^0.20.5

  # Localization
  intl: ^0.19.0

  # Utilities
  path_provider: ^2.1.2
  equatable: ^2.0.5
  http: ^1.1.0

  # Dependency Injection
  get_it: ^7.6.7
  injectable: ^2.3.2

dependency_overrides:
  shared_preferences_android: 2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/models/
